name: تشغيل بوت الكابتشا

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v3

      - name: إعداد Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: تثبيت Tesseract
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr

      - name: تثبيت المتطلبات
        run: pip install -r requirements.txt

      - name: تشغيل البوت
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python3 bot/main.py
